server:
  port: 8030

spring:
  application:
    name: third-party
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.24:8848

alibaba:
  cloud:
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      sts:
        access-key: LTAI5tG49gAtKWteGPnqjhsN
        secret-key: SPeawSl9s3rh3yBN0dBQ9DEIdchPlr

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5tG49gAtKWteGPnqjhsN # 访问身份验证中用到用户标识
    accessKeySecret: SPeawSl9s3rh3yBN0dBQ9DEIdchPlr # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: sky03-mall-demo # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://39.98.190.128:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: mall/images/ # 上传文件夹路径前缀
